sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g @commitlint/travis-cli@^7.0.0
script:
  - npm run test:ci
  - commitlint-travis
  - npm run danger
  - npm pack --loglevel notice
branches:
  except:
    - gh-pages
notifications:
  email: false
env:
  global:
    # travis encrypt --pro DANGER_JS_APP_INSTALL_ID=<value>
    - secure: "WAF3FGsKBq3PmeW9HIORt4dUzO74/GPE6pVaqcg1hpoYvf9vMj6oCsmzPH+arSy1rzRiLl8bYyzVzxctKR16PiZbErcQqVAo/T9WEzdfGMS7duzXt6kShNGvNtjx3VWfwU0vXgLxRejgsFcrH54d3I5fN0ayPfeeUSPSJuNU9DgJW2NzmFyvMK9CGYOwt1Nvme2OTYFM6FSkmNEe2Ckque3DQqMdokTiqWehMGzY5t/QakQqpo8iMUefv3N5Se0N32LI8fdaR6oFkClu4jZkC3RwqyuoEJGWzmdG4/gcrQz8NTe7JF6a+5MGqi9PwbIa+Q+ZE/8cgYWD8fnNOcNgMpJaxUYqFPFhaPPqXqVuKqh3weReYbfXnjPTpgQ6P66IphXgUMTXx79hQ161rhSfjl7j81wz7Fkx2xpTWhrujVkhPOwesJ+E1918pwoMK3L28EkkPjbEtSkfQuTSkuYT72CPWFVm8sIDNHmij1CSTcL2zVNiE7ea6zJNgJF6Ql6J8e+tzPj/K6UWLV3nCyKX0XrBdt5cuHn8mbvyRl0q6F/aEF6LUmBwfCz53aClX710RcnsSJJNvtQDpEFUiyXXNvKPlmuE+TVY4vbhwzatW7N3UZVP6OYrHRw0I2cmabuFl4W3MqZkvsIAblloavMCb2KUeGjV27dNmwS7wqsu/7o="
    # travis encrypt --pro DANGER_GITHUB_API_TOKEN=<value>
    - secure: "ZP9hS3h3vq91K+OZFx2lR57o4oDbHsyjXAcJYrTRqUzJQhJuhWDHyHQF59Rx5GHrzhQh2GbKEpmo+3TyOIKDMIvpTHBnq9+V6KsW7YwoGLISX4xZz6UGDPxufPZPRLqVg4HDmr0AJb84PWEQlmJIpLCPWTmQsK0rimg+jqLDfmqt5UTNRnpiEp3E9L8ea2lAx/U+ugBW6rFgjnb1mLvnq4A1AJkTJmRtangHLezVC9T36o7oDH0kyGHsprkj/UgbYWlQNlcqf4hyZHhJ3+s4JDuqw/zHwjnU7Dh7/Nl/64Z4aYGQkKVGZKNwN8dfIsWFrhm8CGXQK6xHc5VAtqiXy6L6X2mzjedupe2M1Yk5S5/y65rDIr/7npTQUPVkV4NGLlv2J/L95GrDCCsKbWz0aQNuR8N0EvHGp1WEff650VaU9sGhAA5nXRwltuuio1iIAHoPCHNXixgt4evcHd+mQ7eWvLyrYCWR3l6eZGrSXGDNg37csLI7S2slzsEFRBNRtzl62vPSa4JAKLk9/FmbhL/Y/OahPknfDM9uxz7KtKUVT1cp+5O2uFwe83qEjsmC6pJTOzdHrUMrAUuGm4dPd9SRDSt7MJA88TZ4Vb+YTrGLPUDwbB3aYO7d3xLRNtg6x1Sfqev4TlZI8Z3iVPnZVOQSYV+VRsD166AZsILVgMw="
