sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g @commitlint/travis-cli@^7.0.0
script:
  - npm run test:ci
  - commitlint-travis
  - npm pack --loglevel notice
branches:
  except:
    - gh-pages
notifications:
  email: false
