sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g @commitlint/travis-cli@^7.0.0
script:
  - npm run test:ci
  - commitlint-travis
  - npm run danger
  - npm pack --loglevel notice
branches:
  except:
    - gh-pages
notifications:
  email: false
env:
  global:
    # travis encrypt --pro DANGER_JS_APP_INSTALL_ID=<value>
    - secure: "WAF3FGsKBq3PmeW9HIORt4dUzO74/GPE6pVaqcg1hpoYvf9vMj6oCsmzPH+arSy1rzRiLl8bYyzVzxctKR16PiZbErcQqVAo/T9WEzdfGMS7duzXt6kShNGvNtjx3VWfwU0vXgLxRejgsFcrH54d3I5fN0ayPfeeUSPSJuNU9DgJW2NzmFyvMK9CGYOwt1Nvme2OTYFM6FSkmNEe2Ckque3DQqMdokTiqWehMGzY5t/QakQqpo8iMUefv3N5Se0N32LI8fdaR6oFkClu4jZkC3RwqyuoEJGWzmdG4/gcrQz8NTe7JF6a+5MGqi9PwbIa+Q+ZE/8cgYWD8fnNOcNgMpJaxUYqFPFhaPPqXqVuKqh3weReYbfXnjPTpgQ6P66IphXgUMTXx79hQ161rhSfjl7j81wz7Fkx2xpTWhrujVkhPOwesJ+E1918pwoMK3L28EkkPjbEtSkfQuTSkuYT72CPWFVm8sIDNHmij1CSTcL2zVNiE7ea6zJNgJF6Ql6J8e+tzPj/K6UWLV3nCyKX0XrBdt5cuHn8mbvyRl0q6F/aEF6LUmBwfCz53aClX710RcnsSJJNvtQDpEFUiyXXNvKPlmuE+TVY4vbhwzatW7N3UZVP6OYrHRw0I2cmabuFl4W3MqZkvsIAblloavMCb2KUeGjV27dNmwS7wqsu/7o="
    # travis encrypt --pro DANGER_GITHUB_API_TOKEN=<value>
    - secure: "Z98fUnmhaDbkeyN7ohwMm62KSqGjNzxzQoX42Pgm4q0pHXfhJ640QzicqjvojAaf2NXs+my/4/7j/W6YGnvJvehmGdO7biM5IWDc3oTNjhqQEizfAgAPHj93T8NJyJwalr09PcKdkYh1GeNZ34V8ctu4IdLM14stMJyAjep/uvZxI2M+L432dQGIXfvRwnTfzN4+C+ueVpwGcD631+lXsJEfMC6rV3sH1RtYz9tIZABT3xZqzrDoeDd9rMPhhUELpsTtERqFHXocJA3sil2ThCqSAh+8Z3w2y67fPcGoq7IUVHBLCG7C7RGFuya8UKVsDEK9OnDSdfjeSyIJlIGv8i2XxyOdzRLhijYdh3SrbhyrmoW1zRyu6qs/skJRsokEBPhixzPLKsg1nna6jNvTlvXarmAHriXgkRFqNHc813Pyp57aKqIwH5JA5Zy5vO+hri0crlpsro2ARqM5gTRwMmN0l7chqq5omuhp8oGMSW2YgEJ+GCv+vbGv1Ehg3BCqnIweY4rpGwyVhTxKcCKUfLUPsPiI+Kx5k3EPUDapOjmQygrsUKlSXRMf5iQQh0luzid2t3eSeGoaH/lu0dpIkjd6gFsHQ01dlQ2gf7zrSXR0pQO8dDuC9UqpPPFjktbmNtYny1fVm1CKSrZj+s37+ivLRdLDdv7OyTI4PP1+D3Y="
