sudo: false
language: node_js
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g @commitlint/travis-cli@^7.0.0
script:
  - npm run test:ci
  - commitlint-travis
  - npm run danger
  - npm pack --loglevel notice
branches:
  except:
    - gh-pages
notifications:
  email: false
env:
  global:
    # travis encrypt --pro DANGER_JS_APP_INSTALL_ID=<value>
    - secure: "WAF3FGsKBq3PmeW9HIORt4dUzO74/GPE6pVaqcg1hpoYvf9vMj6oCsmzPH+arSy1rzRiLl8bYyzVzxctKR16PiZbErcQqVAo/T9WEzdfGMS7duzXt6kShNGvNtjx3VWfwU0vXgLxRejgsFcrH54d3I5fN0ayPfeeUSPSJuNU9DgJW2NzmFyvMK9CGYOwt1Nvme2OTYFM6FSkmNEe2Ckque3DQqMdokTiqWehMGzY5t/QakQqpo8iMUefv3N5Se0N32LI8fdaR6oFkClu4jZkC3RwqyuoEJGWzmdG4/gcrQz8NTe7JF6a+5MGqi9PwbIa+Q+ZE/8cgYWD8fnNOcNgMpJaxUYqFPFhaPPqXqVuKqh3weReYbfXnjPTpgQ6P66IphXgUMTXx79hQ161rhSfjl7j81wz7Fkx2xpTWhrujVkhPOwesJ+E1918pwoMK3L28EkkPjbEtSkfQuTSkuYT72CPWFVm8sIDNHmij1CSTcL2zVNiE7ea6zJNgJF6Ql6J8e+tzPj/K6UWLV3nCyKX0XrBdt5cuHn8mbvyRl0q6F/aEF6LUmBwfCz53aClX710RcnsSJJNvtQDpEFUiyXXNvKPlmuE+TVY4vbhwzatW7N3UZVP6OYrHRw0I2cmabuFl4W3MqZkvsIAblloavMCb2KUeGjV27dNmwS7wqsu/7o="
    # travis encrypt --pro DANGER_GITHUB_API_TOKEN=<value>
    - secure: "KxALArMy8eGPUj4pwNwo32iBD395i1Xpg89QZ0O+99x3517+0aVVEaNrlZVjb8DKoq6ri4VQJUTYCrHRU1gM3grUaPdWFhYIFJ9maC6XYrAuMjP4MWmsjJKzeAZoCtQacHrO1PHTvIFQe5Q76/v8Pu+YGmk9wuLVQS61fvE21AOzaXKiZ4O7w4qJIhzrWHwS4HL4eNy3050LlPTUdp5V/NVwMZca1mtyGgaCCKkGLJUmGFQkgdln8QKg4fJrVeR1ANlSb/CXgV5lA5z7zt6dEW/rL9jXK2GqcLdtXugKX498bIk1zC7ERqyRli171Pdby8AammKyVFQG4DQ12irYJ2/JHPSi8l2y0FJG08ziewl974UYPpTKwRkSIeRtDwZ9kJb8mE60AGK2+FmODJr+dqawEsOYIA4RJulxY6gZR8S/fNUxSK8v8xyZ9tgTDgCU7bc61PJufktMfjL7wvA+oippIwgEwi4vPOasVGdNKmaYg33WtdVmNhYBx5Os4cLv5stMBLpLWuWK7AUUXxWNZUm5Y/ch0SNufX2acKu0Q2pDjP13lZH5so3fWusHZXOnoMFO6I1rCGptC7CPFd91xdVN+/UHd06I2TgSNLScrmzgAreLLDujnNYB5D342N5uc8TOcNw3p/hKbCuc9tEPi4WZOn++wBDeiiNPbSKiJIY="
